export {default as Home} from './pages/Home'
export {default as Default} from './pages/Default'
export {default as CourseDetail} from './pages/CourseDetail'
export {default as Profile} from './pages/Profile'
export {default as SolveQues} from './pages/SolveQues'
export {default as Register} from './pages/Register'
export {default as Login} from './pages/Login'